
import { Dimensions, Platform, StatusBar, StyleSheet } from "react-native";
import { COLORS, FONTS, SIZES } from "appStyles";
export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.GRAY_50 },
  content: { padding: SIZES.SPACING_MD, paddingBottom: 60 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },

  taskHeader: { marginBottom: SIZES.SPACING_MD },
  taskTitle: { fontSize: 22, fontWeight: "700", color: COLORS.GRAY_900, marginBottom: 8 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  taskTags: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  taskTag: {
    backgroundColor: "#FFF6DA",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  taskTagText: { color: "#836400", fontSize: 11, fontWeight: "600" },
  badge: { paddingVertical: 3, paddingHorizontal: 10, borderRadius: 10 },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "700", textTransform: "uppercase" },
  xpBadge: { paddingVertical: 3, paddingHorizontal: 8, borderRadius: 10, backgroundColor: "#667eea" },
  xpBadgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },

  descriptionCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: SIZES.SPACING_MD,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  descTitle: { fontSize: 15, fontWeight: "600", color: COLORS.GRAY_800, marginBottom: 6 },
  descText: { fontSize: 14, color: COLORS.GRAY_600, lineHeight: 20 },
  examplesCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: SIZES.SPACING_MD,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  examplesTitle: { fontSize: 15, fontWeight: "600", color: COLORS.GRAY_800, marginBottom: 10 },
  exampleItem: {
    backgroundColor: COLORS.GRAY_50,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 4,
  },
  exampleLabel: { fontSize: 13, fontWeight: "700", color: COLORS.GRAY_800 },
  exampleText: { fontSize: 13, color: COLORS.GRAY_600, lineHeight: 18 },
  hiddenExamplesText: { fontSize: 12, color: COLORS.GRAY_400, marginTop: 4 },

  constraintsCard: {
    backgroundColor: "#fff8e1",
    borderRadius: 12,
    padding: SIZES.SPACING_MD,
    marginBottom: 12,
  },
  constraintsTitle: { fontSize: 14, fontWeight: "600", color: "#e65100", marginBottom: 6 },
  constraintItem: { fontSize: 13, color: COLORS.GRAY_700, marginBottom: 4 },

  langSection: { marginBottom: 12 },
  langSectionLabel: { fontSize: 14, fontWeight: "600", color: COLORS.GRAY_700, marginBottom: 8 },
  langRow: { flexDirection: "row", gap: 0, borderRadius: 10, overflow: "hidden", borderWidth: 1, borderColor: COLORS.GRAY_200 },
  langBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: COLORS.WHITE,
    borderRightWidth: 1,
    borderRightColor: COLORS.GRAY_200,
  },
  langBtnActive: { backgroundColor: COLORS.ACCENT },
  langBtnText: { fontSize: 13, fontWeight: "600", color: COLORS.GRAY_600 },
  langBtnTextActive: { color: COLORS.WHITE },

  editorSection: { marginBottom: 12 },
  editorLabel: { fontSize: 14, fontWeight: "600", color: COLORS.GRAY_700, marginBottom: 6 },
  editorWrap: { borderRadius: 12, overflow: "hidden", borderWidth: 1, borderColor: COLORS.GRAY_200 },

  actions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  runBtn: { backgroundColor: COLORS.GRAY_700 },
  submitBtn: { backgroundColor: COLORS.ACCENT },
  actionBtnText: { color: "#fff", fontWeight: "600", fontSize: 14 },

  consoleCard: {
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  consoleTitle: { color: "#aaa", fontSize: 12, marginBottom: 6, fontWeight: "600" },
  consoleText: { color: "#d4d4d4", fontSize: 13, fontFamily: "monospace" },
  constraintErrorsCard: {
    backgroundColor: "#fff4f1",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  constraintErrorsTitle: { fontSize: 12, fontWeight: "600", color: "#c62828", marginBottom: 6 },
  constraintErrorText: { fontSize: 12, color: "#4b2c20", lineHeight: 18 },
  constraintFailLabel: {
    color: "#d32f2f",
    fontSize: 13,
    fontWeight: "600",
    marginVertical: 6,
  },
  resultConstraintCard: {
    backgroundColor: "#fff8eb",
    borderRadius: 10,
    padding: 10,
    marginTop: 6,
  },

  solutionsBtn: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 10,
    padding: 14,
    borderWidth: 2,
    borderColor: COLORS.ACCENT,
    alignItems: "center",
    marginBottom: 12,
  },
  solutionsBtnText: { color: COLORS.ACCENT, fontWeight: "600", fontSize: 14 },

  showResultLink: {
    color: COLORS.ACCENT,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    padding: SIZES.SPACING_LG,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: { fontSize: 18, fontWeight: "700", color: COLORS.GRAY_900 },
  modalClose: { fontSize: 20, color: COLORS.GRAY_400, padding: 4 },

  summary: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: COLORS.GRAY_50,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
  },
  summaryItem: { alignItems: "center", gap: 4 },
  summaryLabel: { fontSize: 12, color: COLORS.GRAY_500 },
  summaryValue: { fontSize: 20, fontWeight: "700", color: COLORS.GRAY_900 },

  resultsList: { maxHeight: 300 },
  resultItem: {
    padding: 10,
    marginBottom: 8,
    borderRadius: 8,
    backgroundColor: COLORS.GRAY_50,
  },
  resultItemPassed: {
    backgroundColor: "#E8F5E9",
  },
  resultItemFailed: {
    backgroundColor: "#FFEBEE",
  },
  resultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  resultIndex: { fontSize: 13, fontWeight: "600", color: COLORS.GRAY_800 },
  resultStatus: { fontSize: 13, fontWeight: "600" },

  modalCloseBtn: {
    marginTop: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.ACCENT,
    borderRadius: 10,
    alignItems: "center",
  },
  modalCloseBtnText: { color: "#fff", fontWeight: "600", fontSize: 15 },

  rankSection: {
    backgroundColor: "#fff8e1",
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
  },
  rankTitle: { fontSize: 14, fontWeight: "700", color: "#e65100", marginBottom: 8 },
  rankInfo: { flexDirection: "row", justifyContent: "space-around" },
  rankText: { fontSize: 13, color: COLORS.GRAY_700 },
  rankValue: { fontSize: 18, fontWeight: "700", color: "#e65100" },

  statisticsBtn: {
    backgroundColor: COLORS.ACCENT,
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
    marginTop: 12,
  },
  statisticsBtnText: { color: "#fff", fontWeight: "600", fontSize: 14 },

  statSection: {
    backgroundColor: COLORS.GRAY_50,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  statSectionTitle: { fontSize: 15, fontWeight: "700", color: COLORS.GRAY_800, marginBottom: 8 },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  statLabel: { fontSize: 13, color: COLORS.GRAY_600 },
  statValue: { fontSize: 13, fontWeight: "600", color: COLORS.GRAY_800 },

  langStatCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.GRAY_200,
  },
  langStatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  langStatLabel: { fontSize: 12, fontWeight: "700", color: COLORS.GRAY_800 },
  langStatCount: { fontSize: 11, color: COLORS.GRAY_500 },
  langStatTime: { fontSize: 11, color: COLORS.GRAY_600, marginBottom: 6 },
  progressBar: {
    height: 6,
    backgroundColor: COLORS.GRAY_200,
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLORS.ACCENT,
    borderRadius: 3,
  },

  histogramContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.GRAY_200,
  },
  histogramTitle: { fontSize: 11, fontWeight: "600", color: COLORS.GRAY_700, marginBottom: 8 },
  histogramBars: { gap: 4 },
  histogramBar: { alignItems: "center" },
  histogramBarLabel: {
    fontSize: 9,
    color: COLORS.GRAY_500,
    width: 80,
  },
  histogramBarTrack: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  histogramBarFill: {
    height: 16,
    borderRadius: 2,
    minWidth: 2,
  },
  histogramBarCount: {
    fontSize: 10,
    fontWeight: "600",
    color: COLORS.GRAY_700,
    minWidth: 16,
  },
  histogramLegend: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.GRAY_200,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 10, color: COLORS.GRAY_600 },
});
