import { StyleSheet } from "react-native";
import { COLORS } from "appStyles";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.WHITE,
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  heroCard: {
    backgroundColor: "#FAFAFA",
    borderColor: "#ECECEC",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  heroOverline: {
    color: "black",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: COLORS.GRAY_900,
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 10,
  },
  heroDescription: {
    color: COLORS.GRAY_600,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    backgroundColor: COLORS.WHITE,
    borderColor: "#EEEEEE",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  summaryValue: {
    color: COLORS.GRAY_900,
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  summaryLabel: {
    color: COLORS.GRAY_500,
    fontSize: 12,
    fontWeight: "600",
  },
  searchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  searchBlock: {
    flex: 1,
    justifyContent: "center",
    position: "relative",
  },
  searchInput: {
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    borderRadius: 18,
    borderWidth: 1,
    color: COLORS.GRAY_DARK,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingRight: 46,
  },
  clearButton: {
    alignItems: "center",
    backgroundColor: "#DADADA",
    borderRadius: 11,
    height: 22,
    justifyContent: "center",
    position: "absolute",
    right: 14,
    width: 22,
  },
  clearButtonText: {
    color: COLORS.GRAY_DARK,
    fontSize: 11,
    fontWeight: "700",
  },
  filterButton: {
    alignItems: "center",
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    borderRadius: 18,
    borderWidth: 1,
    height: 52,
    justifyContent: "center",
    position: "relative",
    width: 56,
  },
  filterBadge: {
    alignItems: "center",
    backgroundColor: COLORS.ACCENT,
    borderRadius: 999,
    height: 20,
    justifyContent: "center",
    position: "absolute",
    right: 6,
    top: 6,
    width: 20,
  },
  filterBadgeText: {
    color: COLORS.WHITE,
    fontSize: 10,
    fontWeight: "700",
  },
  filterIcon: {
    height: 18,
    justifyContent: "space-between",
    width: 18,
  },
  filterLine: {
    backgroundColor: COLORS.GRAY_700,
    borderRadius: 999,
    height: 2,
  },
  filterLineWide: {
    width: 18,
  },
  filterLineMedium: {
    width: 14,
  },
  filterLineShort: {
    width: 10,
  },
  filterDotTop: {
    backgroundColor: COLORS.GRAY_700,
    borderRadius: 999,
    height: 6,
    position: "absolute",
    right: 1,
    top: -2,
    width: 6,
  },
  filterDotMiddle: {
    backgroundColor: COLORS.GRAY_700,
    borderRadius: 999,
    height: 6,
    left: 6,
    position: "absolute",
    top: 6,
    width: 6,
  },
  filterDotBottom: {
    backgroundColor: COLORS.GRAY_700,
    borderRadius: 999,
    height: 6,
    left: 1,
    position: "absolute",
    top: 14,
    width: 6,
  },
  errorBanner: {
    backgroundColor: "#FFF1F2",
    borderColor: "#FFD5D9",
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorBannerText: {
    color: "#9F1239",
    fontSize: 13,
    lineHeight: 18,
  },
  listContent: {
    paddingBottom: 28,
  },
  listContentEmpty: {
    flexGrow: 1,
  },
  centerContainer: {
    alignItems: "center",
    backgroundColor: COLORS.WHITE,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingText: {
    color: COLORS.GRAY_500,
    fontSize: 15,
    marginTop: 12,
  },
  emptyContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  emptyTitle: {
    color: COLORS.GRAY_900,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 10,
    textAlign: "center",
  },
  emptyDescription: {
    color: COLORS.GRAY_500,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  emptyButton: {
    backgroundColor: "#9F0FA7",
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  emptyButtonText: {
    color: COLORS.WHITE,
    fontSize: 14,
    fontWeight: "700",
  },
  modalOverlay: {
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    flex: 1,
    justifyContent: "flex-end",
    padding: 16,
  },
  modalCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 28,
    maxHeight: "88%",
    paddingBottom: 20,
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  modalHandle: {
    alignSelf: "center",
    backgroundColor: "#D7D7D7",
    borderRadius: 999,
    height: 5,
    marginBottom: 14,
    width: 54,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  modalTitle: {
    color: COLORS.GRAY_900,
    fontSize: 22,
    fontWeight: "800",
  },
  modalCloseButton: {
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  modalCloseButtonText: {
    color: COLORS.GRAY_700,
    fontSize: 14,
    fontWeight: "700",
  },
  filterSection: {
    marginBottom: 18,
  },
  filterSectionTitle: {
    color: COLORS.GRAY_900,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  filterInput: {
    backgroundColor: "#F8F8F8",
    borderColor: "#E7E7E7",
    borderRadius: 16,
    borderWidth: 1,
    color: COLORS.GRAY_DARK,
    fontSize: 14,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  rangeRow: {
    flexDirection: "row",
    gap: 10,
  },
  rangeInput: {
    flex: 1,
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  secondaryActionButton: {
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 16,
    flex: 1,
    justifyContent: "center",
    minHeight: 50,
  },
  secondaryActionButtonText: {
    color: COLORS.GRAY_700,
    fontSize: 14,
    fontWeight: "700",
  },
  primaryActionButton: {
    alignItems: "center",
    backgroundColor: COLORS.ACCENT,
    borderRadius: 16,
    flex: 1,
    justifyContent: "center",
    minHeight: 50,
  },
  primaryActionButtonText: {
    color: COLORS.WHITE,
    fontSize: 14,
    fontWeight: "700",
  },
});
