import { StyleSheet } from "react-native";
import { COLORS } from "appStyles";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.WHITE,
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  heroCard: {
    backgroundColor: "#FAFAFA",
    borderColor: "#ECECEC",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  heroOverline: {
    color: COLORS.ACCENT,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: COLORS.GRAY_900,
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 10,
  },
  heroDescription: {
    color: COLORS.GRAY_600,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    backgroundColor: COLORS.WHITE,
    borderColor: "#EEEEEE",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  summaryValue: {
    color: COLORS.GRAY_900,
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  summaryLabel: {
    color: COLORS.GRAY_500,
    fontSize: 12,
    fontWeight: "600",
  },
  searchBlock: {
    justifyContent: "center",
    marginBottom: 12,
    position: "relative",
  },
  searchInput: {
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    borderRadius: 18,
    borderWidth: 1,
    color: COLORS.GRAY_DARK,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingRight: 46,
  },
  clearButton: {
    alignItems: "center",
    backgroundColor: "#DADADA",
    borderRadius: 11,
    height: 22,
    justifyContent: "center",
    position: "absolute",
    right: 14,
    width: 22,
  },
  clearButtonText: {
    color: COLORS.GRAY_DARK,
    fontSize: 11,
    fontWeight: "700",
  },
  errorBanner: {
    backgroundColor: "#FFF1F2",
    borderColor: "#FFD5D9",
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorBannerText: {
    color: "#9F1239",
    fontSize: 13,
    lineHeight: 18,
  },
  listContent: {
    paddingBottom: 28,
  },
  listContentEmpty: {
    flexGrow: 1,
  },
  centerContainer: {
    alignItems: "center",
    backgroundColor: COLORS.WHITE,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingText: {
    color: COLORS.GRAY_500,
    fontSize: 15,
    marginTop: 12,
  },
  emptyContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  emptyTitle: {
    color: COLORS.GRAY_900,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 10,
    textAlign: "center",
  },
  emptyDescription: {
    color: COLORS.GRAY_500,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  emptyButton: {
    backgroundColor: COLORS.GRAY_DARK,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  emptyButtonText: {
    color: COLORS.WHITE,
    fontSize: 14,
    fontWeight: "700",
  },
});
